from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from Dialogs.changePassword import *
from Dialogs.Notice.NoticeList import *
from Dialogs.Message.MessageDialog import *
from Dialogs.events import *
from Dialogs.superadmin.Dispensaries.new_DispensaryProfile import *

class dispensaryHome(object):
    def setup(self, dispensaryHome,loginData = None):
        self.logindata = loginData
        import requests
        URL = "http://127.0.0.1:8000/api/dispensaries/"
        data = {
            "username" : self.logindata["id"]
        }
        r = requests.get(url=URL,params=data)
        l = r.json()
        self.dispensarydata = l[0]
        dispensaryHome.setObjectName("dispensaryHome")
        dispensaryHome.resize(1366, 786)
        dispensaryHome.setStyleSheet("")
        dispensaryHome.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(dispensaryHome)
        self.centralwidget.setObjectName("centralwidget")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(1300, 10, 50, 50))
        self.logout.setMinimumSize(QtCore.QSize(50, 50))
        self.logout.setMaximumSize(QtCore.QSize(50, 50))
        self.logout.setStyleSheet("border:none;")
        self.logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../MDTouch/Images/LogoutIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout.setIcon(icon)
        self.logout.setIconSize(QtCore.QSize(50, 50))
        self.logout.setObjectName("logout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(550, 20, 281, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(0, 50))
        self.title.setMaximumSize(QtCore.QSize(400, 70))
        self.title.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.title.setObjectName("title")
        self.deleteIdInput = QtWidgets.QLineEdit(self.centralwidget)
        self.deleteIdInput.setGeometry(QtCore.QRect(1050, 340, 151, 31))
        self.deleteIdInput.setStyleSheet("background : rgb(255,255,255);")
        self.deleteIdInput.setObjectName("deleteIdInput")
        self.setMedicineIdInput = QtWidgets.QLineEdit(self.centralwidget)
        self.setMedicineIdInput.setGeometry(QtCore.QRect(1050, 410, 131, 31))
        self.setMedicineIdInput.setStyleSheet("background : rgb(255,255,255);")
        self.setMedicineIdInput.setText("")
        self.setMedicineIdInput.setObjectName("setMedicineIdInput")
        self.setQuantityButton = QtWidgets.QPushButton(self.centralwidget)
        self.setQuantityButton.setGeometry(QtCore.QRect(1050, 440, 251, 31))
        self.setQuantityButton.setStyleSheet("background : rgb(225,225,225);")
        self.setQuantityButton.setObjectName("setQuantityButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(1200, 340, 101, 31))
        self.deleteButton.setStyleSheet("background : rgb(225,225,225);")
        self.deleteButton.setObjectName("deleteButton")
        self.quantityInput = QtWidgets.QLineEdit(self.centralwidget)
        self.quantityInput.setGeometry(QtCore.QRect(1180, 410, 121, 31))
        self.quantityInput.setStyleSheet("background : rgb(255,255,255);")
        self.quantityInput.setText("")
        self.quantityInput.setObjectName("quantityInput")
        self.viewBills = QtWidgets.QPushButton(self.centralwidget)
        self.viewBills.setGeometry(QtCore.QRect(70, 330, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewBills.sizePolicy().hasHeightForWidth())
        self.viewBills.setSizePolicy(sizePolicy)
        self.viewBills.setMinimumSize(QtCore.QSize(100, 100))
        self.viewBills.setMaximumSize(QtCore.QSize(100, 100))
        self.viewBills.setStyleSheet("border:none;")
        self.viewBills.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../MDTouch/Images/search_prescription.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewBills.setIcon(icon1)
        self.viewBills.setIconSize(QtCore.QSize(100, 100))
        self.viewBills.setObjectName("viewBills")
        self.events = QtWidgets.QPushButton(self.centralwidget)
        self.events.setGeometry(QtCore.QRect(70, 520, 100, 100))
        self.events.setMinimumSize(QtCore.QSize(100, 100))
        self.events.setMaximumSize(QtCore.QSize(100, 100))
        self.events.setStyleSheet("border:none;")
        self.events.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../MDTouch/Images/event.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.events.setIcon(icon2)
        self.events.setIconSize(QtCore.QSize(100, 100))
        self.events.setObjectName("events")
        self.createBill = QtWidgets.QPushButton(self.centralwidget)
        self.createBill.setGeometry(QtCore.QRect(80, 140, 100, 100))
        self.createBill.setMinimumSize(QtCore.QSize(100, 100))
        self.createBill.setMaximumSize(QtCore.QSize(120, 120))
        self.createBill.setStyleSheet("border:none;")
        self.createBill.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../MDTouch/Images/write_bill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createBill.setIcon(icon3)
        self.createBill.setIconSize(QtCore.QSize(100, 100))
        self.createBill.setObjectName("createBill")
        self.addMedicine = QtWidgets.QPushButton(self.centralwidget)
        self.addMedicine.setGeometry(QtCore.QRect(1050, 140, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMedicine.sizePolicy().hasHeightForWidth())
        self.addMedicine.setSizePolicy(sizePolicy)
        self.addMedicine.setMinimumSize(QtCore.QSize(100, 100))
        self.addMedicine.setMaximumSize(QtCore.QSize(100, 100))
        self.addMedicine.setStyleSheet("border:none;")
        self.addMedicine.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../MDTouch/Images/medicines.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addMedicine.setIcon(icon4)
        self.addMedicine.setIconSize(QtCore.QSize(100, 100))
        self.addMedicine.setObjectName("addMedicine")
        self.changePassword = QtWidgets.QPushButton(self.centralwidget)
        self.changePassword.setGeometry(QtCore.QRect(1200, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changePassword.sizePolicy().hasHeightForWidth())
        self.changePassword.setSizePolicy(sizePolicy)
        self.changePassword.setMinimumSize(QtCore.QSize(100, 100))
        self.changePassword.setMaximumSize(QtCore.QSize(100, 100))
        self.changePassword.setStyleSheet("border:none;")
        self.changePassword.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../MDTouch/Images/change_password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.changePassword.setIcon(icon5)
        self.changePassword.setIconSize(QtCore.QSize(100, 100))
        self.changePassword.setObjectName("changePassword")
        self.profile = QtWidgets.QPushButton(self.centralwidget)
        self.profile.setGeometry(QtCore.QRect(1050, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile.sizePolicy().hasHeightForWidth())
        self.profile.setSizePolicy(sizePolicy)
        self.profile.setMinimumSize(QtCore.QSize(100, 100))
        self.profile.setMaximumSize(QtCore.QSize(100, 100))
        self.profile.setStyleSheet("border:none;")
        self.profile.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../MDTouch/Images/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile.setIcon(icon6)
        self.profile.setIconSize(QtCore.QSize(100, 100))
        self.profile.setObjectName("profile")
        self.inbox = QtWidgets.QPushButton(self.centralwidget)
        self.inbox.setGeometry(QtCore.QRect(1230, 10, 50, 50))
        self.inbox.setMinimumSize(QtCore.QSize(50, 50))
        self.inbox.setMaximumSize(QtCore.QSize(50, 50))
        self.inbox.setStyleSheet("border:none;")
        self.inbox.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../MDTouch/Images/inbox_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inbox.setIcon(icon7)
        self.inbox.setIconSize(QtCore.QSize(50, 50))
        self.inbox.setObjectName("inbox")
        self.notices = QtWidgets.QPushButton(self.centralwidget)
        self.notices.setGeometry(QtCore.QRect(1200, 140, 100, 100))
        self.notices.setMinimumSize(QtCore.QSize(100, 100))
        self.notices.setMaximumSize(QtCore.QSize(100, 100))
        self.notices.setStyleSheet("border:none;")
        self.notices.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../MDTouch/Images/notices.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notices.setIcon(icon8)
        self.notices.setIconSize(QtCore.QSize(100, 100))
        self.notices.setObjectName("notices")
        self.noticesLabel = QtWidgets.QLabel(self.centralwidget)
        self.noticesLabel.setGeometry(QtCore.QRect(1200, 250, 101, 31))
        self.noticesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.noticesLabel.setObjectName("noticesLabel")
        self.addMedicineLabel = QtWidgets.QLabel(self.centralwidget)
        self.addMedicineLabel.setGeometry(QtCore.QRect(1050, 240, 111, 71))
        self.addMedicineLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addMedicineLabel.setObjectName("addMedicineLabel")
        self.changePasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.changePasswordLabel.setGeometry(QtCore.QRect(1190, 630, 131, 61))
        self.changePasswordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.changePasswordLabel.setObjectName("changePasswordLabel")
        self.profileLabel = QtWidgets.QLabel(self.centralwidget)
        self.profileLabel.setGeometry(QtCore.QRect(1050, 630, 101, 31))
        self.profileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.profileLabel.setObjectName("profileLabel")
        self.createBillLabel = QtWidgets.QLabel(self.centralwidget)
        self.createBillLabel.setGeometry(QtCore.QRect(50, 240, 141, 31))
        self.createBillLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.createBillLabel.setObjectName("createBillLabel")
        self.viewBillsLabel = QtWidgets.QLabel(self.centralwidget)
        self.viewBillsLabel.setGeometry(QtCore.QRect(45, 430, 141, 31))
        self.viewBillsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.viewBillsLabel.setObjectName("viewBillsLabel")
        self.eventsLabel = QtWidgets.QLabel(self.centralwidget)
        self.eventsLabel.setGeometry(QtCore.QRect(50, 630, 141, 31))
        self.eventsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.eventsLabel.setObjectName("eventsLabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(240, 150, 771, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.MedicineSearchTable = QtWidgets.QTableWidget(self.frame)
        self.MedicineSearchTable.setGeometry(QtCore.QRect(0, 29, 771, 511))
        self.MedicineSearchTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MedicineSearchTable.setAutoFillBackground(False)
        self.MedicineSearchTable.setStyleSheet("background: rgb(225,225,255);\n"
"text-align : left;")
        self.MedicineSearchTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.MedicineSearchTable.setAutoScrollMargin(100)
        self.MedicineSearchTable.setShowGrid(True)
        self.MedicineSearchTable.setWordWrap(True)
        self.MedicineSearchTable.setCornerButtonEnabled(True)
        self.MedicineSearchTable.setRowCount(5)
        self.MedicineSearchTable.setColumnCount(6)
        self.MedicineSearchTable.setObjectName("MedicineSearchTable")
        item = QtWidgets.QTableWidgetItem()
        self.MedicineSearchTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MedicineSearchTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MedicineSearchTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MedicineSearchTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MedicineSearchTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MedicineSearchTable.setHorizontalHeaderItem(5, item)
        self.MedicineSearchTable.horizontalHeader().setCascadingSectionResizes(False)
        self.MedicineSearchTable.horizontalHeader().setStretchLastSection(True)
        self.searchInput = QtWidgets.QLineEdit(self.frame)
        self.searchInput.setGeometry(QtCore.QRect(0, 0, 421, 31))
        self.searchInput.setStyleSheet("background : rgb(255,255,255);")
        self.searchInput.setObjectName("searchInput")
        self.filterComboBox = QtWidgets.QComboBox(self.frame)
        self.filterComboBox.setGeometry(QtCore.QRect(420, 0, 211, 31))
        self.filterComboBox.setStyleSheet("background : rgb(225,225,225);")
        self.filterComboBox.setObjectName("filterComboBox")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.searchButton = QtWidgets.QPushButton(self.frame)
        self.searchButton.setGeometry(QtCore.QRect(630, 0, 141, 31))
        self.searchButton.setStyleSheet("background : rgb(225,225,225);")
        self.searchButton.setObjectName("searchButton")
        self.dispensaryName = QtWidgets.QLabel(self.centralwidget)
        self.dispensaryName.setGeometry(QtCore.QRect(110, 30, 400, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispensaryName.sizePolicy().hasHeightForWidth())
        self.dispensaryName.setSizePolicy(sizePolicy)
        self.dispensaryName.setMinimumSize(QtCore.QSize(100, 30))
        self.dispensaryName.setMaximumSize(QtCore.QSize(400, 100))
        self.dispensaryName.setStyleSheet("font-size:15pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.dispensaryName.setObjectName("dispensaryName")
        dispensaryHome.setCentralWidget(self.centralwidget)

        self.retranslateUi(dispensaryHome)
        QtCore.QMetaObject.connectSlotsByName(dispensaryHome)

    def retranslateUi(self, dispensaryHome):
        _translate = QtCore.QCoreApplication.translate
        dispensaryHome.setWindowTitle(_translate("dispensaryHome", "MainWindow"))
        self.title.setText(_translate("dispensaryHome", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25pt; font-weight:600; text-decoration: underline;\">MDTouch</span></p></body></html>"))
        self.deleteIdInput.setPlaceholderText(_translate("dispensaryHome", "Enter Medicine Id"))
        self.setMedicineIdInput.setPlaceholderText(_translate("dispensaryHome", "Enter Medicine Id"))
        self.setQuantityButton.setText(_translate("dispensaryHome", "SET QUANTITY"))
        self.deleteButton.setText(_translate("dispensaryHome", "DELETE"))
        self.quantityInput.setPlaceholderText(_translate("dispensaryHome", "Quantity"))
        self.noticesLabel.setText(_translate("dispensaryHome", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Notices</span></p></body></html>"))
        self.addMedicineLabel.setText(_translate("dispensaryHome", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Add<br>Medicine</span></p></body></html>"))
        self.changePasswordLabel.setText(_translate("dispensaryHome", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Change<br/>Password</span></p></body></html>"))
        self.profileLabel.setText(_translate("dispensaryHome", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Profile</span></p></body></html>"))
        self.createBillLabel.setText(_translate("dispensaryHome", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Create Bill</span></p></body></html>"))
        self.viewBillsLabel.setText(_translate("dispensaryHome", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">View Bills</span></p></body></html>"))
        self.eventsLabel.setText(_translate("dispensaryHome", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Events</span></p></body></html>"))
        item = self.MedicineSearchTable.horizontalHeaderItem(0)
        item.setText(_translate("dispensaryHome", "Medicine ID"))
        item = self.MedicineSearchTable.horizontalHeaderItem(1)
        item.setText(_translate("dispensaryHome", "Name"))
        item = self.MedicineSearchTable.horizontalHeaderItem(2)
        item.setText(_translate("dispensaryHome", "Quantity"))
        item = self.MedicineSearchTable.horizontalHeaderItem(3)
        item.setText(_translate("dispensaryHome", "Batch No"))
        item = self.MedicineSearchTable.horizontalHeaderItem(4)
        item.setText(_translate("dispensaryHome", "Expiry Date"))
        item = self.MedicineSearchTable.horizontalHeaderItem(5)
        item.setText(_translate("dispensaryHome", "Manufacturing Date"))
        self.searchInput.setPlaceholderText(_translate("dispensaryHome", "Search for Medicines"))
        self.filterComboBox.setItemText(0, _translate("dispensaryHome", "Search By Name"))
        self.filterComboBox.setItemText(1, _translate("dispensaryHome", "All medicines"))
        self.filterComboBox.setItemText(2, _translate("dispensaryHome", "Search By  Id"))
        self.filterComboBox.setItemText(3, _translate("dispensaryHome", "Search by Batch Id"))
        self.filterComboBox.setItemText(4, _translate("dispensaryHome", "Sort by Mf Date"))
        self.filterComboBox.setItemText(5, _translate("dispensaryHome", "Sort by Expiry Date"))
        self.searchButton.setText(_translate("dispensaryHome", "SEARCH"))
        self.dispensaryName.setText(_translate("dispensaryHome", "dispensary_name"))
        self.dispensaryName.setText(str(self.dispensarydata["name"]))

        self.clickEvents(dispensaryHome)

    def clickEvents(self, parent):
        self.logout.clicked.connect(lambda : self.clickOnLogoutButton(parent))
        self.changePassword.clicked.connect(lambda : self.clickOnChangePassword(parent))
        self.notices.clicked.connect(lambda : self.clickOnNotice())
        self.inbox.clicked.connect(lambda : self.clickOnMessages(parent))
        self.events.clicked.connect(lambda : self.clickOnEvents())
        self.profile.clicked.connect(lambda : self.clickOnProfile(parent))

    def clickOnLogoutButton(self,parent):
        parent.loginpage.setup(parent)

    def clickOnChangePassword(self,parent):
        self.window = QDialog()
        self.dialog = changePassword()
        self.dialog.setup(self.window,self.logindata,self)
        self.window.setModal(True)
        self.window.show()

    def clickOnNotice(self):
        self.window = QDialog()
        self.dialog = noticeList()
        self.dialog.setup(self.window)
        self.window.setModal(True)
        self.window.show()

    def clickOnMessages(self,parent):
        self.window = QDialog()
        self.dialog = messageDialog()
        self.dialog.setup(self.window, self.logindata)
        self.window.setModal(True)
        self.window.show()

    def clickOnEvents(self):
        self.window = QDialog()
        self.dialog = eventsDialog()
        self.dialog.setup(self.window,'DS',self.dispensarydata)
        self.window.setModal(True)
        self.window.show()

    def clickOnProfile(self,parent):
        self.window = QDialog()
        self.dialog = new_dispensaryProfile()
        self.dialog.setup(self.window,self.dispensarydata)
        self.window.setModal(True)
        self.window.show()
